Repository Alfresco/rest-api-explorer, pull requests merged in 2020-06, with the labels that each got.

#90 [REPO-5169] API Node Definitions
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#93 Feature/repo 5169 api compiled models
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#95 Revert "Feature/repo 5169 api compiled models"
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#96 Revert "[REPO-5169] API Node Definitions"
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#97 [REPO-5169] Added Definition to node API
  src/main/webapp/definitions/alfresco-core.yaml
Labels: ACS 7.0, PR: draft, PR: partially-approved

#94 ACS-306: ACS Repository: V1 Rest API for content direct access urls
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#98 ACS-306: ACS Repository: V1 Rest API for content direct access urls
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed
