Repository Alfresco/rest-api-explorer, pull requests merged in 2020-11, with the labels that each got.

#108 [ACS-777] Email notification for digital workspace
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#111 MNT-22036 : Add versionedEnabled flag
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#112 MNT-22036 : Add versionedEnabled flag
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#113 Remove duplicated '#/parameters/nodeIdWithAliasParam'
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed
