Repository Alfresco/rest-api-explorer, pull requests merged in 2021-08, with the labels that each got.

#109 ACS-599 OpenAPI spec for Direct access urls API
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#130 ACS-566 Fix Poms
  pom.xml
Labels: PR: reviewed-approved

#133 [release] 7.1.0-A2
  pom.xml
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#134 [release] 7.1.0-A3
  pom.xml
Labels: PR: reviewed-approved
