Repository Alfresco/rest-api-explorer, pull requests merged in 2022-07, with the labels that each got.

#162 [MNT-22106] Missing parenthesis in filter description
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#161 ACS-3183 POST rules, GET, PUT and DELETE rule API definition.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#159 [ACS-3194] API for linked rules
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#160 ACS-3208: improve documentation for condition support
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#164 ACS-3250 PUT endpoint for rule reordering.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#166 ACS-3252 Refactor rule sets to handle ownership, inheritance and linking.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#167 ACS-3251 Rule inheritance and run rules.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#168 ACS-3357 Get single rule set.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed
