Repository Alfresco/rest-api-explorer, pull requests merged in 2022-10, with the labels that each got.

#176 ACS-3605 The option rule set field linkedToBy may be restricted by the server for performance reasons.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#178 ACS-3572 Action Constraints endpoint
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#179 ACS-3726: Removing rule related endpoints
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: reviewed-approved

#180 ACS-3689 [release] 7.3.0
  .travis.yml
Labels: PR: partially-approved
