Repository Alfresco/rest-api-explorer, pull requests merged in 2022-09, with the labels that each got.

#171 ACS-3363 Update description of inheritedBy.
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: partially-approved

#173 ACS-3525: API for manual triggering rules on a folder
  src/main/webapp/definitions/alfresco-core.yaml
Labels: PR: unreviewed

#172 ACS-3560 Add CustomEmbeddedWorkflow to Discovery API
  src/main/webapp/definitions/alfresco-discovery.yaml
Labels: PR: reviewed-approved

#175 ACS-3560 [release] 7.3.0-A1
  .travis.yml
Labels: PR: reviewed-approved
